# -*- coding: utf-8 -*-
"""Untitled56.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EhbvgHhwps3444d-6A6ppJLizkGDOlRh
"""

!pip install gurobipy

import time
import numpy as np
import gurobipy as gp
from gurobipy import GRB

# ============================================================
# Imports
# ============================================================

import time
import numpy as np
import gurobipy as gp
from gurobipy import GRB

# ============================================================
# Optional: Gurobi Web License Service setup
# Only use this block if you have WLS credentials.
# Otherwise, skip it and use env = None.
# ============================================================

USE_WLS = False

if USE_WLS:
    params = {
        "WLSACCESSID": "your_access_id",
        "WLSSECRET": "your_secret",
        "LICENSEID": your_license_id,   # integer, no quotation marks
    }

    env = gp.Env(params=params)
else:
    env = None

# ============================================================
# Create random LP instances
# We solve 100 instances with the same feasible region
# but different objective vectors.
# ============================================================

np.random.seed(0)

m_constraints = 200
n_variables = 500
n_instances = 100

A = np.random.rand(m_constraints, n_variables)

# Make the feasible region safely nonempty.
# Since x = 0 is feasible for Ax <= b and x >= 0,
# choose positive RHS.
b = 50 + 50 * np.random.rand(m_constraints)

# 100 different objective vectors
cost_vectors = [
    np.random.rand(n_variables)
    for _ in range(n_instances)
]

# ============================================================
# Approach 1: Rebuild model from scratch for every instance
# ============================================================

def solve_by_rebuilding(A, b, cost_vectors, env=None):
    times = []
    obj_values = []

    m_constraints, n_variables = A.shape

    for k, c in enumerate(cost_vectors):
        start = time.perf_counter()

        if env is None:
            model = gp.Model()
        else:
            model = gp.Model(env=env)

        model.Params.OutputFlag = 0

        x = model.addVars(n_variables, lb=0, name="x")

        for i in range(m_constraints):
            model.addConstr(
                gp.quicksum(A[i, j] * x[j] for j in range(n_variables)) <= b[i],
                name=f"constr_{i}"
            )

        model.setObjective(
            gp.quicksum(c[j] * x[j] for j in range(n_variables)),
            GRB.MINIMIZE
        )

        model.optimize()

        end = time.perf_counter()

        times.append(end - start)

        if model.status == GRB.OPTIMAL:
            obj_values.append(model.objVal)
        else:
            obj_values.append(None)

    return times, obj_values

# ============================================================
# Approach 2: Build once and reuse fixed constraints
# Only update objective coefficients.
# ============================================================

def solve_by_reusing(A, b, cost_vectors, env=None):
    times = []
    obj_values = []

    m_constraints, n_variables = A.shape

    if env is None:
        model = gp.Model()
    else:
        model = gp.Model(env=env)

    model.Params.OutputFlag = 0

    x = model.addVars(n_variables, lb=0, name="x")

    for i in range(m_constraints):
        model.addConstr(
            gp.quicksum(A[i, j] * x[j] for j in range(n_variables)) <= b[i],
            name=f"constr_{i}"
        )

    model.ModelSense = GRB.MINIMIZE
    model.update()

    for k, c in enumerate(cost_vectors):
        start = time.perf_counter()

        for j in range(n_variables):
            x[j].Obj = c[j]

        model.optimize()

        end = time.perf_counter()

        times.append(end - start)

        if model.status == GRB.OPTIMAL:
            obj_values.append(model.objVal)
        else:
            obj_values.append(None)

    return times, obj_values

# ============================================================
# Run comparison
# ============================================================

rebuild_times, rebuild_objs = solve_by_rebuilding(
    A, b, cost_vectors, env=env
)

reuse_times, reuse_objs = solve_by_reusing(
    A, b, cost_vectors, env=env
)

# ============================================================
# Print results
# ============================================================

total_rebuild_time = sum(rebuild_times)
total_reuse_time = sum(reuse_times)

avg_rebuild_time = np.mean(rebuild_times)
avg_reuse_time = np.mean(reuse_times)

speedup = total_rebuild_time / total_reuse_time

print("===== Computation Time Comparison for 100 Instances =====")

print("\nApproach 1: Rebuild model each time")
print(f"Total time   : {total_rebuild_time:.4f} seconds")
print(f"Average time : {avg_rebuild_time:.4f} seconds")

print("\nApproach 2: Reuse fixed constraints")
print(f"Total time   : {total_reuse_time:.4f} seconds")
print(f"Average time : {avg_reuse_time:.4f} seconds")

print("\nSpeedup")
print(f"Reusing is approximately {speedup:.2f}x faster")

# ============================================================
# Check that both approaches give the same objective values
# ============================================================

max_difference = 0.0

for obj1, obj2 in zip(rebuild_objs, reuse_objs):
    if obj1 is not None and obj2 is not None:
        max_difference = max(max_difference, abs(obj1 - obj2))

print(f"Maximum objective difference: {max_difference:.6e}")

# ============================================================
# Optional: Plot computation times
# ============================================================

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
plt.plot(rebuild_times, marker="o", label="Rebuild model")
plt.plot(reuse_times, marker="s", label="Reuse model")
plt.xlabel("Instance number")
plt.ylabel("Time in seconds")
plt.title("Computation time comparison")
plt.legend()
plt.grid(True)
plt.show()